version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__HOST=localhost:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost/
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__server__OFFLINE_MODE=false
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=your-secret-key-here
      - GITEA__actions__ENABLED=true
      - GITEA__actions__DEFAULT_ACTIONS_URL=https://gitea.com
      - GITEA__actions__ENABLE_ACTIONS_RUNNER=true
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/data
    ports:
      - "80:3000"
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:15
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres_data:/var/lib/postgresql/data

  act-runner:
    image: gitea/act_runner:latest
    container_name: gitea-act-runner
    restart: "no"
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=RTgsoGkdleDSMxILLJJHA2AGzozwT7iCgYv3tPn6
      - GITEA_RUNNER_NAME=gitea-runner
      - GITEA_RUNNER_LABELS=ubuntu-latest:docker://node:18-bullseye,ubuntu-22.04:docker://node:18-bullseye,ubuntu-20.04:docker://node:16-bullseye
      - GITEA_RUNNER_WORK_DIR=/workspace
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace_data:/workspace
    depends_on:
      - gitea
    privileged: true

networks:
  gitea:
    external: false

volumes:
  gitea_data:
    driver: local
  postgres_data:
    driver: local
  workspace_data:
    driver: local 