services:
  goapp:
    build:
      context: ./
      dockerfile: ./Dockerfile.go
    image: justsu
    expose:
      - "5000"
    networks:
      - intnet

  apache:
    build:
      context: ./
      dockerfile: ./Dockerfile.apache
    image: justapache
    expose:
      - "8888"
    depends_on:
      - goapp
    networks:
      - intnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - apache
      - goapp
    networks:
      - intnet

networks:
  intnet:
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1 