FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y apache2 apache2-utils && rm -rf /var/lib/apt/lists/*
WORKDIR /root/
COPY app/apache/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY app/apache/init-apache.sh /init-apache.sh
RUN chmod +x /init-apache.sh
EXPOSE 8888
CMD ["/init-apache.sh"] 